//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int ID_documento { get; set; }
        public string Codigo { get; set; }
        public string Documento { get; set; }
        public Nullable<int> ID_empleado { get; set; }
        public string Dpt_origen { get; set; }
        public string Dpt_destino { get; set; }
        public string Fecha { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
